### ISSUE TITLE
Swift Sandbox is not working anymore

### ISSUE THREAD

**Issue by chingi3** [isaced/awesome-cocoa-weekly#1]
Hi there, Swift Sandbox http://swiftsandbox.io/ is not working anymore :(
![2016-11-27 15 05 59](https://cloud.githubusercontent.com/assets/606467/20647148/76d432b4-b4ae-11e6-9e8a-c5661e6b0da4.png)

**Comment by isaced** [comment]
Thanks for the reminder, I've removed it.
